kind: Deployment
apiVersion: apps/v1
metadata:
  name: mongo-deployment
  namespace: chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      name: chat-app
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo
          ports:
            - containerPort: 27017
          env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: root
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: admin
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
         - name: mongo-data
           persistentVolumeClaim:
             claimName: mongo-pvc

